// Supabase Edge Function: generate or personalize an article server-side with
// the project's own Claude key, so app users don't each need to paste one.
//
// Deploy:  supabase functions deploy personalize
// Secret:  supabase secrets set ANTHROPIC_API_KEY=sk-ant-...
// Auth:    verify_jwt is on by default, so only signed-in users can call it.
//
// Modes (chosen from the request body):
//   - generate:    { mode: 'generate', topic, difficulty, language, targetMinutes } -> { title, body }
//   - personalize: { title, body[], difficulty, language, targetMinutes }           -> { body }

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';

const cors = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const MODEL = 'claude-haiku-4-5-20251001';

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors });

  try {
    const { title, body, topic, language, difficulty, targetMinutes, mode, languageLevel, fieldLevel, focus, priorReflection } = await req.json();
    const apiKey = Deno.env.get('ANTHROPIC_API_KEY');
    if (!apiKey) return json({ error: 'Server AI key not configured' }, 500);

    const hasBody = Array.isArray(body) && body.length > 0;
    const generate = mode === 'generate' || (topic && !hasBody);
    const focusInstr = focusLine(focus, languageLevel, fieldLevel);

    const reflectionInstr = typeof priorReflection === 'string' && priorReflection.trim()
      ? ` The reader wrote this reflection after their last article: "${priorReflection.trim().slice(0, 300)}" — acknowledge or build on it where it fits naturally.`
      : '';
    const prompt = generate
      ? `Write an engaging, factual ~${(targetMinutes ?? 5) >= 15 ? 900 : 500}-word article for a ${difficulty}-level ${language} learner about: ${topic}. ${focusInstr}${reflectionInstr} Adjust vocabulary and sentence complexity appropriately. Make it genuinely interesting and self-contained. Then add learning scaffolding drawn from THIS article. Respond with ONLY a JSON object (no markdown fences, no preamble): {"title": string, "body": string[], "vocabulary": [{"word": string, "definition": string}], "quiz": [{"type":"mc","q":string,"opts":[string,string,string,string],"correct":number,"explanation":string},{"type":"mc","q":string,"opts":[string,string,string,string],"correct":number,"explanation":string},{"type":"open","q":string,"placeholder":string}], "branches": [{"title":string,"description":string}]}. "vocabulary": 4-6 useful terms from the article for a ${languageLevel ?? 'A2'} learner — high-frequency words slightly above their level; no proper nouns. "quiz": two multiple-choice then one open; option wording must stay at the article's language level; "correct" is the 0-based index; "explanation" is one short sentence on why the correct option is right. "branches": 4-5 related next topics.`
      : `You are helping someone learn ${language} by reading about a topic they care about.
Rewrite the article below for a "${difficulty}" reading level, about ${targetMinutes} minutes long.
${focusInstr}
Keep the meaning and key facts; adjust vocabulary and sentence complexity to the level.
Return ONLY the rewritten article as plain paragraphs separated by blank lines — no preamble, no title.

Title: ${title}

${(body ?? []).join('\n\n')}`;

    const text = await callClaude(apiKey, prompt, generate ? 2800 : 1500);

    if (generate) {
      const obj = extractJson(text);
      const out = obj && Array.isArray(obj.body) && obj.body.length ? obj.body : paragraphs(text);
      return json({
        title: obj?.title ?? topic,
        body: out,
        quiz: obj?.quiz ?? [],
        vocabulary: obj?.vocabulary ?? [],
        branches: obj?.branches ?? [],
        note: `Generated by Claude (hosted) · ${topic} · ${difficulty}`,
      });
    }

    const paras = paragraphs(text);
    return json({ body: paras.length ? paras : body, note: `Personalized by Claude (hosted) · ${language} · ${difficulty}` });
  } catch (e) {
    return json({ error: String(e) }, 400);
  }
});

async function callClaude(apiKey: string, prompt: string, maxTokens: number): Promise<string> {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'x-api-key': apiKey, 'anthropic-version': '2023-06-01' },
    body: JSON.stringify({ model: MODEL, max_tokens: maxTokens, messages: [{ role: 'user', content: prompt }] }),
  });
  if (!res.ok) throw new Error(`Anthropic ${res.status}`);
  const data = await res.json();
  return data?.content?.[0]?.text ?? '';
}

// deno-lint-ignore no-explicit-any
function extractJson(text: string): any {
  const m = text.match(/\{[\s\S]*\}/);
  if (!m) return null;
  try {
    return JSON.parse(m[0]);
  } catch {
    return null;
  }
}

function paragraphs(text: string): string[] {
  return String(text)
    .split(/\n\n+/)
    .map((p) => p.trim())
    .filter(Boolean);
}

// Concrete calibration anchors per CEFR level (mirrors apps/mobile/src/ai/llm.ts).
const CEFR_ANCHORS: Record<string, string> = {
  A1: 'very short sentences (under 8 words), present tense, only the ~500 most common words',
  A2: 'short sentences (under 12 words), simple present and past, the ~1000 most common words',
  B1: 'everyday vocabulary plus common abstract words, occasional subordinate clauses',
  B2: 'varied sentence structure, common idioms, vocabulary roughly within the Oxford 3000',
  C1: 'complex sentences, nuanced vocabulary, natural idiomatic phrasing',
  C2: 'full native range: sophisticated vocabulary and layered argument structure',
};

function cefrAnchor(level?: string): string {
  const l = level ?? 'A2';
  return `CEFR ${l} (${CEFR_ANCHORS[l] ?? CEFR_ANCHORS.A2})`;
}

// Alternating-focus instruction (CLAUDE.md §7): push one ladder, hold the other.
function focusLine(focus?: string, languageLevel?: string, fieldLevel?: number): string {
  if (focus === 'language') {
    return `Focus on LANGUAGE: keep the subject approachable, but deliberately stretch vocabulary and sentence structure toward ${cefrAnchor(languageLevel)}.`;
  }
  if (focus === 'field') {
    return `Focus on FIELD: hold the language at ${cefrAnchor(languageLevel)}, but go deeper into the subject — introduce and explain more specialized concepts (depth ${fieldLevel ?? 2} of 5, where 1 explains everything from scratch and 5 assumes professional familiarity).`;
  }
  return '';
}

function json(payload: unknown, status = 200) {
  return new Response(JSON.stringify(payload), { status, headers: { ...cors, 'content-type': 'application/json' } });
}
