// Supabase Edge Function: generate or personalize an article server-side with
// the project's own Claude key, so app users don't each need to paste one.
//
// Deploy:  supabase functions deploy personalize
// Secret:  supabase secrets set ANTHROPIC_API_KEY=sk-ant-...
// Auth:    verify_jwt is on by default, so only signed-in users can call it.
//
// Modes (chosen from the request body):
//   - generate:    { mode: 'generate', topic, difficulty, language, targetMinutes } -> { title, body }
//   - personalize: { title, body[], difficulty, language, targetMinutes }           -> { body }

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';

const cors = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const MODEL = 'claude-haiku-4-5-20251001';

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors });

  try {
    const { title, body, topic, language, difficulty, targetMinutes, mode } = await req.json();
    const apiKey = Deno.env.get('ANTHROPIC_API_KEY');
    if (!apiKey) return json({ error: 'Server AI key not configured' }, 500);

    const hasBody = Array.isArray(body) && body.length > 0;
    const generate = mode === 'generate' || (topic && !hasBody);

    const prompt = generate
      ? `Write an engaging, factual ~${(targetMinutes ?? 5) >= 15 ? 900 : 500}-word article for a ${difficulty}-level ${language} learner about: ${topic}. Adjust vocabulary and sentence complexity to the level. Make it genuinely interesting and self-contained. Respond with ONLY a JSON object: {"title": string, "body": string[]} where "body" is an array of paragraph strings. No markdown fences, no preamble.`
      : `You are helping someone learn ${language} by reading about a topic they care about.
Rewrite the article below for a "${difficulty}" reading level, about ${targetMinutes} minutes long.
Keep the meaning and key facts; adjust vocabulary and sentence complexity to the level.
Return ONLY the rewritten article as plain paragraphs separated by blank lines — no preamble, no title.

Title: ${title}

${(body ?? []).join('\n\n')}`;

    const text = await callClaude(apiKey, prompt, generate ? 2000 : 1500);

    if (generate) {
      const obj = extractJson(text);
      const out = obj && Array.isArray(obj.body) && obj.body.length ? obj.body : paragraphs(text);
      return json({ title: obj?.title ?? topic, body: out, note: `Generated by Claude (hosted) · ${topic} · ${difficulty}` });
    }

    const paras = paragraphs(text);
    return json({ body: paras.length ? paras : body, note: `Personalized by Claude (hosted) · ${language} · ${difficulty}` });
  } catch (e) {
    return json({ error: String(e) }, 400);
  }
});

async function callClaude(apiKey: string, prompt: string, maxTokens: number): Promise<string> {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'x-api-key': apiKey, 'anthropic-version': '2023-06-01' },
    body: JSON.stringify({ model: MODEL, max_tokens: maxTokens, messages: [{ role: 'user', content: prompt }] }),
  });
  if (!res.ok) throw new Error(`Anthropic ${res.status}`);
  const data = await res.json();
  return data?.content?.[0]?.text ?? '';
}

// deno-lint-ignore no-explicit-any
function extractJson(text: string): any {
  const m = text.match(/\{[\s\S]*\}/);
  if (!m) return null;
  try {
    return JSON.parse(m[0]);
  } catch {
    return null;
  }
}

function paragraphs(text: string): string[] {
  return String(text)
    .split(/\n\n+/)
    .map((p) => p.trim())
    .filter(Boolean);
}

function json(payload: unknown, status = 200) {
  return new Response(JSON.stringify(payload), { status, headers: { ...cors, 'content-type': 'application/json' } });
}
